---
- hosts: all
  remote_user: root
  gather_facts: False
  vars:
  tasks:
    - name: installing various
      pkg: name={{ item }} state=latest
      with_items:
        - apt-key

    - name: Add an apt key by id from a keyserver
      apt_key:
        keyserver: keyserver.ubuntu.com:80 
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5 

    - apt_repository:
        repo: deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.6 main
        state: present

    - name: installing various mongo-db packages
      apt: name={{ item }} state=latest
      with_items:
        - mongodb-org
        - mongodb-org-server
        - mongodb-org-mongos
        - mongodb-org-shell
        - mongodb-org-tools

    - name: Copy bashrc
      copy:
        src: ~/Repos/cm/ansible/antsle/mongodb/files/bashrc
        dest: /root/.bashrc
        owner: root
        group: root
        mode: 0774


# EOF
