---
- hosts: all
  remote_user: root
  gather_facts: False
  vars:
    go_download_location: https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz
    go_tarball: go1.9.2.linux-amd64.tar.gz
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - name: Install pyton pip
      apt: name={{ item }} state=latest
      with_items:
          - python-pip
          - python-dev
          - build-essential
    - name: Pip install various packages
      pip: name={{ item }} 
      with_items:
        - Flask
        - requests
        - nose
        - cassandra-driver
        - coverage
        - cqlsh
    - name: installing various
      apt: name={{ item }} state=latest
      with_items:
        - build-essential
        - lua5.2
        - netcat
    - name: install rust
      shell: curl https://sh.rustup.rs -y -sSf | sh
      tags: skip
    - name: Copy motd
      copy: 
        src: ~/Repos/cm/ansible/antsle/devbox/files/motd
        dest: /etc/motd
        owner: root
        group: root
        mode: 0774
        backup: yes
      tags: 
        - skip 
        - updatefiles
    - name: Copy .bashrc
      copy: 
        src: ~/Repos/cm/ansible/antsle/devbox/files/bashrc 
        dest: /root/.bashrc
        owner: root
        group: root
        mode: 0774
        backup: yes
      tags: 
        - skip 
        - updatefiles
    - name: Copy .vimrc
      copy: 
        src: ~/Repos/cm/ansible/antsle/devbox/files/vimrc
        dest: /root/.vimrc
        owner: root
        group: root
        mode: 0774
        backup: yes
      tags: 
        - skip 
        - updatefiles
    - name: Create /root/bin
      file: path=/root/bin/ state=directory
      tags: 
        - updatefiles
    - name: Copy scripts to ~/bin
      copy: 
        src: ~/Repos/cm/ansible/antsle/devbox/files/{{ item }}
        dest: /root/bin/CQLSH.sh
        owner: root
        group: root
        mode: 0774
        backup: yes
      with_items:
        - CQLSH.sh
        - CQLSH_FILE.sh
      tags: 
        - skip 
        - updatefiles
    - name: Download the Go tarball
      get_url:
        url: "{{ go_download_location }}"
        dest: /usr/local/src/{{ go_tarball }}
      tags: skip
    - name: Extract the Go tarball if Go is not yet installed or not the desired version
      unarchive:
        src: /usr/local/src/{{ go_tarball }}
        dest: /usr/local
        copy: no
      tags: skip
# TODO:
# - add MOTD to say what is installed
# - install GIT
# - 
