---
- hosts: cassandra
  remote_user: root
  become: yes
  tasks:
    - name: install git
      apt: state=present name=git
      tags: git
    - name: clone code repo
      git: repo=https://github.com/mayelespino/code.git
           dest=~/code
           force=yes
           recursive=no
      tags: git
    - name: install other packages and looping through all packages
      action: apt pkg={{item}} state=installed update_cache=yes
      with_items:
        - python-dev
        - python-setuptools
        - git-core
    - name: install pip
      action: easy_install name=pip
    - name: install various libraries with pip
      action: pip name={{item}} state=present
      with_items: 
        - cassandra-driver
        - cql


