---
- hosts: all
  remote_user: root
  tasks:
  - name: Install libselinux-python
    package: 
        name: libselinux-python
        state: latest
  - name: Create hadoop group
    group:
        name: hadoop
        state: present
  - name: Create hduser group
    group:
        name: hduser
        state: present
  - name: Add hadoop user to groups
    user:
        name: hadoop
        groups: hadoop,hduser
  - name: Change hadoop password to hadoop
    user: name=hadoop password=$1$some_pla$XqmShyOixZFoNchG5ut/j/ state=present
  - name: Create ~/hadoop/.ssh
    file: path=/home/hadoop/.ssh state=directory
  - name: Add hadoop's pub key to authorized_keys
    copy: src=files/authorized_keys dest=/home/hadoop/.ssh/
        owner: hadoop
        group: hadoop
        mode: 777
  - name: Create .ssh/known_hosts
    shell: touch /home/hadoop/.ssh/known_hosts
  - name: Install java 1.6
    package:
        name: java-1.8.0-openjdk-src.x86_64
        state: latest
        mode: 777
  - name: Untar hadoop-2.7.4.tar.gz
    unarchive:
        src: "http://mirrors.advancedhosters.com/apache/hadoop/common/stable/hadoop-2.7.4.tar.gz"
        dest: /opt/
        copy: no
  - name: Copy bashrc to hadoop's home directory
    copy: src=files/bashrc dest=/home/hadoop/.bashrc
        owner: hadoop
        group: hadoop
  - name: Create /opt/hadoop-2.7.4/input
    file: path=/opt/hadoop-2.7.4/input state=directory
    tags: test
  - name: copy files to /opt/hadoop-2.7.4/input
    copy:
        src: /opt/hadoop-2.7.4/etc/hadoop/*.xml
        dest: /opt/hadoop-2.7.4/input/
        owner: hadoop
        group: hadoop
        mode: 777
        remote_src: yes
  - name: Copy files to remote host
    copy: 
        src: "{{ item }}"
        dest: /opt/hadoop-2.7.4/etc/hadoop
        owner: hadoop
        group: hadoop
        mode: 777
    with_fileglob:
        - files/*.xml
    tags: test
  - name: Format hadoop fs
    shell: /opt/hadoop-2.7.4/bin/hdfs namenode -format

