---
- hosts: all
  remote_user: root
  tasks:
  - name: Copy bashrc to hadoop's home directory
    copy: src=files/bashrc dest=~/.bashrc
        owner: root
        group: root
        mode: 775
  - name: Copy files to remote host
    copy: 
        src: "{{ item }}"
        dest: ~/bin/
        owner: root
        group: root
        mode: 775
    with_fileglob:
        - bin/*
